name: qenv
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _x86_64-microarch-level=3
  - absl-py=2.3.1
  - alsa-lib=1.2.13
  - aom=3.9.1
  - astunparse=1.6.3
  - attr=2.5.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.2
  - certifi=2026.1.4
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - contourpy=1.3.2
  - cpython=3.12.8
  - cuda-crt-tools=12.8.61
  - cuda-cudart=12.8.57
  - cuda-cudart_linux-64=12.8.57
  - cuda-cuobjdump=12.8.55
  - cuda-cupti=12.8.57
  - cuda-nvcc-tools=12.8.61
  - cuda-nvdisasm=12.8.55
  - cuda-nvrtc=12.8.61
  - cuda-nvtx=12.8.55
  - cuda-nvvm-tools=12.8.61
  - cuda-version=12.8
  - cudnn=9.10.1.4
  - cusparselt=0.7.0.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.13.6
  - double-conversion=3.3.1
  - expat=2.6.4
  - filelock=3.17.0
  - flatbuffers=24.12.23
  - fluidsynth=2.3.7
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.0
  - freetype=2.13.3
  - fsspec=2025.2.0
  - gast=0.6.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.67.1
  - h2=4.2.0
  - h5py=3.14.0
  - harfbuzz=10.1.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - jack=1.9.22
  - jinja2=3.1.5
  - keras=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.4
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libavif16=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcublas=12.8.3.14
  - libcudnn=9.10.1.4
  - libcudnn-dev=9.10.1.4
  - libcudss0=0.4.0.2
  - libcufft=11.3.3.41
  - libcufile=1.13.0.11
  - libcups=2.3.3
  - libcurand=10.3.9.55
  - libcurl=8.14.1
  - libcusolver=11.7.2.55
  - libcusparse=12.5.7.53
  - libdb=6.2.32
  - libdeflate=1.23
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libgrpc=1.67.1
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm19=19.1.7
  - libllvm20=20.1.0.rc1
  - liblzma=5.6.3
  - libmad=0.15.1b
  - libmagma=2.8.0
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjitlink=12.8.61
  - libogg=1.3.5
  - libopengl=1.7.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.5
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsndfile=1.2.2
  - libsqlite=3.50.3
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=256.9
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libudev1=257.3
  - libuuid=2.38.1
  - libuv=1.50.0
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - lz4-c=1.10.0
  - markdown=3.8.2
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - mdurl=0.1.2
  - mkl=2024.2.2
  - ml_dtypes=0.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - namex=0.1.0
  - nccl=2.27.6.1
  - ncurses=6.5
  - networkx=3.4.2
  - numpy=2.2.3
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.6.0
  - opt_einsum=3.4.0
  - optree=0.14.0
  - opusfile=0.12
  - packaging=25.0
  - pcre2=10.44
  - pillow=11.1.0
  - pip=24.3.1
  - pixman=0.44.2
  - portaudio=19.6.0
  - portmidi=2.0.4
  - protobuf=5.28.3
  - psutil=7.2.1
  - pthread-stubs=0.4
  - pulseaudio-client=17.0
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pyside6=6.8.1
  - pysocks=1.7.1
  - python=3.12.8
  - python-dateutil=2.9.0.post0
  - python-flatbuffers=25.2.10
  - python_abi=3.12
  - qhull=2020.2
  - qt6-main=6.8.1
  - rav1e=0.6.6
  - rdma-core=55.0
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.4
  - rich=14.0.0
  - sdl2=2.30.10
  - sdl2_image=2.8.2
  - sdl2_mixer=2.6.3
  - sdl2_ttf=2.22.0
  - setuptools=75.6.0
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.2
  - svt-av1=2.3.0
  - sympy=1.13.3
  - tbb=2021.13.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.0
  - tensorflow-base=2.18.0
  - tensorflow-estimator=2.18.0
  - termcolor=3.1.0
  - tk=8.6.13
  - tornado=6.5.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - wayland=1.23.1
  - websockets=15.0.1
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.2
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zipp=3.23.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.2.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.15.1.9
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.28.9
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - pathfinding==1.0.16
      - pygame==2.6.0
      - torch==2.11.0.dev20260122+cu128
      - torchaudio==2.11.0.dev20260122+cu128
      - torchvision==0.25.0.dev20260122+cu128
      - triton==3.6.0+git9844da95
prefix: /home/eamon/miniforge3/envs/qenv
